{{- if .Values.sshBastionServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssh-bastion-server.name" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ssh-bastion-server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ssh-bastion-server.name" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "ssh-bastion-server.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ssh-bastion-server.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
