---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "primehub-shared-space.tusd.name" . }}-hooks
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "primehub-shared-space.tusd.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- tpl (.Files.Glob "scripts/shared-space/*").AsConfig . | nindent 2 }}
