{{- if eq (include "rclone.enabled" .) "true" -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "primehub.store.pvcName" .}}
  labels:
    app.kubernetes.io/name: {{ include "primehub.name" . }}-store
    helm.sh/chart: {{ include "primehub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    name: {{ include "primehub.store.pvcName" .}}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 64Gi
  storageClassName: rclone
  csi:
    driver: csi-rclone
    volumeHandle: data-id
    volumeAttributes:
      remote: "s3"
      remotePath: {{ include "primehub.store.bucket" .}}
      s3-provider: "Minio"
      s3-endpoint: {{ include "primehub.store.endpoint" .}}
      s3-access-key-id: {{ include "primehub.store.accessKey" .}}
      s3-secret-access-key: {{ include "primehub.store.secretKey" .}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "primehub.store.pvcName" .}}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: rclone
  selector:
    matchLabels:
      name: {{ include "primehub.store.pvcName" .}}
{{- end }}
