{{- if eq (include "minio.enabled" .) "true" -}}
{{ $bucketRoot := or ($.Values.minio.bucketRoot) ($.Values.minio.mountPath) }}
apiVersion: {{ template "minio.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: {{ .Values.minio.DeploymentUpdate.type }}
    {{- if eq .Values.minio.DeploymentUpdate.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.minio.DeploymentUpdate.maxSurge }}
      maxUnavailable: {{ .Values.minio.DeploymentUpdate.maxUnavailable }}
    {{- end}}
  {{- if .Values.minio.s3gateway.enabled }}
  replicas: {{ .Values.minio.s3gateway.replicas }}
  {{- end }}
  {{- if .Values.minio.gcsgateway.enabled }}
  replicas: {{ .Values.minio.gcsgateway.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "minio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "minio.fullname" . }}
      labels:
        app: {{ template "minio.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/minio/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/minio/configmap.yaml") . | sha256sum }}
    spec:
  {{- if .Values.minio.priorityClassName }}
      priorityClassName: "{{ .Values.minio.priorityClassName }}"
  {{- end }}
      serviceAccountName: {{ include "minio.serviceAccountName" . | quote }}
{{- if and .Values.minio.securityContext.enabled .Values.minio.persistence.enabled }}
      securityContext:
        runAsUser: {{ .Values.minio.securityContext.runAsUser }}
        runAsGroup: {{ .Values.minio.securityContext.runAsGroup }}
        fsGroup: {{ .Values.minio.securityContext.fsGroup }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          {{- if .Values.minio.s3gateway.enabled }}
          command: [ "/bin/sh",
          "-ce",
          "/usr/bin/docker-entrypoint.sh minio -S {{ .Values.minio.certsPath }} gateway s3 {{ .Values.minio.s3gateway.serviceEndpoint }} {{- template `minio.extraArgs` . }}" ]
          {{- else }}
          {{- if .Values.minio.gcsgateway.enabled }}
          command: [ "/bin/sh",
          "-ce",
          "/usr/bin/docker-entrypoint.sh minio -S {{ .Values.minio.certsPath }} gateway gcs {{ .Values.minio.gcsgateway.projectId }} {{- template `minio.extraArgs` . }}" ]
          {{- else }}
          command: [ "/bin/sh",
          "-ce",
          "/usr/bin/docker-entrypoint.sh minio -S {{ .Values.minio.certsPath }} server {{ $bucketRoot }} {{- template `minio.extraArgs` . }}" ]
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if and .Values.minio.persistence.enabled (not .Values.minio.gcsgateway.enabled) (not .Values.minio.s3gateway.enabled) }}
            - name: export
              mountPath: {{ .Values.minio.mountPath }}
              {{- if .Values.minio.persistence.subPath }}
              subPath: "{{ .Values.minio.persistence.subPath }}"
              {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.minio.existingSecret }}{{ .Values.minio.existingSecret }}{{ else }}{{ template "minio.fullname" . }}{{ end }}
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.minio.existingSecret }}{{ .Values.minio.existingSecret }}{{ else }}{{ template "minio.fullname" . }}{{ end }}
                  key: secretkey
            {{- if .Values.minio.gcsgateway.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/credentials/gcs_key.json"
            {{- end }}
            {{- if .Values.minio.s3gateway.enabled -}}
            {{- if .Values.minio.s3gateway.accessKey }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.minio.existingSecret }}{{ .Values.minio.existingSecret }}{{ else }}{{ template "minio.fullname" . }}{{ end }}
                  key: awsAccessKeyId
            {{- end }}
            {{- if .Values.minio.s3gateway.secretKey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.minio.existingSecret }}{{ .Values.minio.existingSecret }}{{ else }}{{ template "minio.fullname" . }}{{ end }}
                  key: awsSecretAccessKey
            {{- end }}
            {{- end }}
            {{- range $key, $val := .Values.minio.environment }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.minio.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.minio.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.minio.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.minio.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.minio.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: http
            initialDelaySeconds: {{ .Values.minio.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.minio.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.minio.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.minio.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.minio.readinessProbe.failureThreshold }}
          resources:
{{ toYaml .Values.minio.resources | indent 12 }}
{{- with .Values.minio.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.minio.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.minio.imagePullSecrets | nindent 8 }}
{{- end }}
{{- with .Values.minio.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.minio.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      volumes:
        {{- if and (not .Values.minio.gcsgateway.enabled) (not .Values.minio.s3gateway.enabled) }}
        - name: export
        {{- if .Values.minio.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.minio.persistence.existingClaim | default (include "minio.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- end }}
        - name: minio-user
          secret:
            secretName: {{ if .Values.minio.existingSecret }}{{ .Values.minio.existingSecret }}{{ else }}{{ template "minio.fullname" . }}{{ end }}
{{- end }}
