{{- if eq (include "minio.enabled" .) "true" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "minio.fullname" . }}-make-bucket-job
  labels:
    app: {{ template "minio.name" . }}-make-bucket-job
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: {{ template "minio.name" . }}-make-bucket-job
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
{{- if .Values.minio.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.minio.nodeSelector | indent 8 }}
{{- end }}
{{- with .Values.minio.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.minio.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      volumes:
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: {{ template "minio.fullname" . }}
            - secret:
                name: {{ if .Values.minio.existingSecret }}{{ .Values.minio.existingSecret }}{{ else }}{{ template "minio.fullname" . }}{{ end }}
      containers:
      - name: minio-mc
        image: "{{ .Values.minio.mcImage.repository }}:{{ .Values.minio.mcImage.tag }}"
        imagePullPolicy: {{ .Values.minio.mcImage.pullPolicy }}
        command: ["/bin/sh", "/config/initialize"]
        env:
          - name: MINIO_ENDPOINT
            value: {{ template "minio.fullname" . }}
          - name: MINIO_PORT
            value: {{ .Values.minio.service.port | quote }}
        volumeMounts:
          - name: minio-configuration
            mountPath: /config
        resources:
{{ toYaml .Values.minio.resources | indent 10 }}
{{- end }}
