{{- if eq (include "minio.enabled" .) "true" -}}
{{- if not .Values.minio.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accesskey: {{include "primehub.store.accessKey" . | b64enc}}
  secretkey: {{include "primehub.store.secretKey" . | b64enc}}
{{- if .Values.minio.gcsgateway.enabled }}
  gcs_key.json: {{ .Values.minio.gcsgateway.gcsKeyJson | b64enc }}
{{- end }}
{{- if .Values.minio.s3gateway.enabled -}}
{{- if .Values.minio.s3gateway.accessKey }}
  awsAccessKeyId: {{ .Values.minio.s3gateway.accessKey | b64enc | quote }}
{{- end }}
{{- if .Values.minio.s3gateway.secretKey }}
  awsSecretAccessKey: {{ .Values.minio.s3gateway.secretKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
