{{- if .Values.primehub.store.enabled }}
{{- if not .Values.minio.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accesskey: {{ if .Values.minio.accessKey }}{{ .Values.minio.accessKey | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  secretkey: {{ if .Values.minio.secretKey }}{{ .Values.minio.secretKey | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
{{- if .Values.minio.gcsgateway.enabled }}
  gcs_key.json: {{ .Values.minio.gcsgateway.gcsKeyJson | b64enc }}
{{- end }}
{{- if .Values.minio.s3gateway.enabled -}}
{{- if .Values.minio.s3gateway.accessKey }}
  awsAccessKeyId: {{ .Values.minio.s3gateway.accessKey | b64enc | quote }}
{{- end }}
{{- if .Values.minio.s3gateway.secretKey }}
  awsSecretAccessKey: {{ .Values.minio.s3gateway.secretKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- if .Values.minio.etcd.clientCert }}
  etcd_client_cert.pem: {{ .Values.minio.etcd.clientCert | b64enc | quote }}
{{- end }}
{{- if .Values.minio.etcd.clientCertKey }}
  etcd_client_cert_key.pem: {{ .Values.minio.etcd.clientCertKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
