primehub:
  deployKeycloak: true
  keycloak:
    realm: primehub
    client: jupyterhub
    clientAdmin: primehub
    clientMaintenanceProxy: maintenance-proxy
  user: phuser
  password: randstring
  bootstrap:
    enabled: true
    image:
      repository: gcr.io/google-containers/hyperkube-amd64
      tag: v1.14.0

jupyterhub:
  hub:
    extraEnv:
    - name: PRIMEHUB_KEYCLOAK_URL
      valueFrom:
        secretKeyRef:
          name: primehub-secret
          key: keycloak.url
    - name: PRIMEHUB_KEYCLOAK_REALM
      value: primehub
    - name: PRIMEHUB_KEYCLOAK_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: primehub-secret
          key: keycloak.clientId
    - name: PRIMEHUB_KEYCLOAK_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: primehub-secret
          key: keycloak.clientSecret
    extraContainers:
    - name: statsd-to-prometheus
      image: prom/statsd-exporter:v0.9.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 9102
      - containerPort: 9125
        protocol: UDP
    extraConfig:
      primehub: |
        # This attribute is supposed to be inlined while chart building.
        # For dev installing from directory, please use option
        # '--set-file helm/primehub/jupyterhub_primehub.py' of helm install
        # to overwrite this attribute.

  auth:
    state:
      cryptoKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      enabled: true
    type: custom
    custom:
      className: PrimeHubAuthenticator

  proxy:
    secretToken: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  prePuller:
    hook:
      enabled: false
  singleuser:
    extraEnv:
      JUPYTER_ENABLE_LAB: "yes"
      CULL_TIMEOUT: "7200"
      CULL_KERNEL_TIMEOUT: "3600"
      CULL_INTERVAL: "300"
      CULL_CONNECTED: "1"
    profileList:
      - display_name: "Shared, CPU node"
        description: "cpu node"
        kubespawner_override:
          singleuser_image_spec: jupyter/minimal-notebook
      - display_name: "GPU node"
        description: "gpu node, if your cluster enabled gpu"
        kubespawner_override:
          singleuser_image_spec: jupyter/minimal-notebook
          extra_resource_limits:
            nvidia.com/gpu: "1"

keycloak:
  keycloak:
    replicas: 1
    image:
      repository: jboss/keycloak
      tag: 4.8.3.Final
    password: CHANGEKEYCLOAKPASSWORD

  postgresql:
    persistence:
      enabled: false
    postgresPassword: CHANGEKEYCLOAKPASSWORD

  # this is used for keycloak subchart, as the condition
  persistence:
    deployPostgres: false

  test:
    enabled: false

admin-notebook:
  proxy:
    extraEnv:
      - name: KC_BASE
        valueFrom:
          secretKeyRef:
            name: primehub-secret
            key: keycloak.url
      - name: KC_REALM
        value: primehub
      - name: KC_URL
        value: $(KC_BASE)/auth/realms/$(KC_REALM)
      - name: KC_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: primehub-secret
            key: keycloak.clientMaintenanceProxyId
      - name: KC_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: primehub-secret
            key: keycloak.clientMaintenanceProxySecret
