{{- if .Values.graphql.image.credentials }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "primehub.graphql.pullSecret" . }}
kind: Secret
metadata:
  name: {{ include "primehub.name" . }}-graphql-pull-secret
type: kubernetes.io/dockerconfigjson
{{- end }}
---
apiVersion: v1
data:
{{- if .Values.graphql.sharedGraphqlSecret }}
  sharedSecret: {{ .Values.graphql.sharedGraphqlSecret | b64enc }}
{{- else }}
  sharedSecret: {{ randAlphaNum 32 | b64enc }}
{{- end }}
{{- if .Values.store.enabled }}
  storeAccessKey: {{ include "primehub.store.accessKey" . | b64enc }}
  storeSecretKey: {{ include "primehub.store.secretKey" . | b64enc }}
{{- end }}
kind: Secret
metadata:
  name: {{ include "primehub.name" . }}-graphql
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- if not .Values.graphql.sharedGraphqlSecret }}
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
    {{- end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
