apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "admin-notebook.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admin-notebook.name" . }}
    helm.sh/chart: {{ include "admin-notebook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "admin-notebook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "admin-notebook.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          args:
            - jupyter
            - notebook
            - --ip
            - "0.0.0.0"
            - --port
            - "8888"
            - --NotebookApp.token=''
            - --NotebookApp.base_url={{ .Values.baseUrl | quote}}
            - --NotebookApp.default_url='/notebooks/index.ipynb'
            - --NotebookApp.allow_origin={{ .Values.allowOrigin }}
          env:
           - name: PATH
             value: ~/bin:~/.local/bin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.proxy.enabled }}
        # keycloak gateway is a proxy to secure application. For more information, please see
        # https://www.keycloak.org/docs/4.8/securing_apps/index.html#_keycloak_generic_adapter
        - name: proxy
          image: keycloak/keycloak-gatekeeper:6.0.1
          args:
            - --discovery-url=$(KC_URL)
            {{- if .Values.proxy.enableRefreshToken }}
            - --enable-refresh-tokens=true
            - --enable-encrypted-token=true
            - --encryption-key={{ .Values.proxy.encryptionKey }}
            {{- else }}
            - --secure-cookie=false
            {{- end }}
            - --client-id=$(KC_CLIENT_ID)
            - --client-secret=$(KC_CLIENT_SECRET)
            - --listen=0.0.0.0:8080
            - --base-uri={{ .Values.baseUrl }}
            - --oauth-uri=/oauth
            - --resources=uri=/*|roles=realm-management:realm-admin
            - --upstream-url=http://127.0.0.1:8888
            - --verbose={{ .Values.proxy.verbose }}
          env:
{{- if .Values.proxy.extraEnv }}
{{ toYaml .Values.proxy.extraEnv | indent 12 }}
{{- end }}
          ports:
            - name: web
              containerPort: 8080
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}
{{- end }}
{{- with .Values.extraContainers }}
{{ tpl . $ | indent 8 }}
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      serviceAccountName: {{ include "admin-notebook.fullname" . }}
