apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-notebook.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admin-notebook.name" . }}
    helm.sh/chart: {{ include "admin-notebook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.proxy.enabled }}8080{{ else }}8888{{ end }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "admin-notebook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
