{{- if .Values.keycloak.deploy }}
{{ if and (.Values.keycloak.prometheus.operator.prometheusRules.enabled) (.Values.keycloak.prometheus.operator.prometheusRules.rules) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.keycloak.prometheus.operator.prometheusRules.selector | nindent 4 }}
spec:
  groups:
  - name: {{ include "keycloak.fullname" . }}
    rules:
      {{- toYaml .Values.keycloak.prometheus.operator.prometheusRules.rules | nindent 6 }}
{{- end }}
{{- end }}
