{{- if .Values.keycloak.deploy }}
{{- if not .Values.keycloak.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-http
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- if not .Values.keycloak.password }}
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
    {{- end }}
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{ include "keycloak.passwordKey" . }}: {{ include "keycloak.password" . }}
{{- end}}
{{- end }}
