{{- if .Values.keycloak.deploy }}
{{- if and (not .Values.keycloak.persistence.deployPostgres) (not .Values.keycloak.persistence.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-db
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{ include "keycloak.dbPasswordKey" . }}: {{ include "keycloak.dbPassword" . | b64enc | quote }}
  {{ include "keycloak.dbUserKey" . }}: {{ .Values.keycloak.persistence.dbUser | b64enc | quote }}
{{- end -}}
{{- end }}
