version: 2

jobs:
  unit_test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            # checkout submodules
            git submodule init && git submodule sync && git submodule update --init --recursive && git submodule status

            # create venv
            python3 -m venv .venv
            source .venv/bin/activate

            # run tests
            cd chart
            pip install -r ../vendor/zero-to-jupyterhub-k8s/images/hub/requirements.txt --upgrade
            pip install pytest-cov
            make test-html

            # upload artifacts
            mkdir -p /tmp/artifacts
            mv htmlcov /tmp/artifacts/

      - store_artifacts:
          path: /tmp/artifacts

  e2e:
    docker:
      - image: circleci/buildpack-deps:jessie-curl-dind
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: e2e
          environment:
            EXECUTE_E2E_TEST: "true"
          command: |
            ./ci/ci-test.sh

  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "d0:90:27:9c:dc:28:b5:3e:d8:18:0c:9a:64:46:6f:d4"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}

      - run:
          name: publish
          command: |
            ./ci/publish.sh

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"

workflows:
  version: 2
  release_builds:
    jobs:
      #- unit_test
      - e2e
      - build:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
