apiVersion: v1
kind: ConfigMap
metadata:
  name: home-config
data:
  home-config.yaml: |
    {{- if .Values.console.homeConfig }}
    {{- .Values.console.homeConfig | nindent 4}}
    {{- else}}
    {{- tpl (.Files.Get "scripts/console/home-config.yaml") . | nindent 4 }}
    {{- end }}
