{{- if .Values.admission.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primehub-admission
  namespace: {{ .Release.Namespace }}
  labels:
    app: primehub-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primehub-admission
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: primehub-admission
    spec:
      serviceAccountName: primehub-admission
      containers:
      - name: primehub-admission
        image: "{{ .Values.admission.image.repository }}:{{ .Values.admission.image.tag }}"
        ports:
        - containerPort: 443
        imagePullPolicy: {{ .Values.admission.image.pullPolicy }}
        resources:
          {{- toYaml .Values.admission.resources | nindent 10 }}
        env:
        - name: GRAPHQL_ENDPOINT
          value: {{ include "primehub.graphql.endpoint" . }}
        - name: GRAPHQL_SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "primehub.name" . }}-graphql-shared-secret
              key: sharedSecret
        - name: IMAGE_PREFIX
          value: {{ .Values.admission.podImageReplacing.imagePrefix }}
        - name: FLASK_DEBUG
          value: "false"
        - name: LOGURU_LEVEL
          value: INFO
        volumeMounts:
          - name: certs
            mountPath: /app/ssl
            readOnly: true
        securityContext:
          runAsUser: 0
      volumes:
        - name: certs
          secret:
            secretName: primehub-admission-webhook-certs
{{- end }}
