{{- if .Values.admission.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: primehub-admission
  name: primehub-admission
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: primehub-admission
  sessionAffinity: None
  type: ClusterIP
{{- end }}
