primehub:
  domain: primehub.example.com
  user: phuser
  password: randstring
jupyterhub:
  auth:
    state:
      cryptoKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  proxy:
    secretToken: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/app-root: http://primehub.example.com/hub/home
      nginx.ingress.kubernetes.io/use-port-in-redirects: true
    hosts:
    - primehub.example.com
    path: /hub
keycloak:
  keycloak:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - primehub.example.com
      path: /auth
    persistence:
      dbVendor: postgres
      deployPostgres: true
      dbPassword: CHANGEKEYCLOAKPASSWORD
  persistence:
    deployPostgres: true
  postgresql:
    persistence:
      enabled: true
    postgresPassword: CHANGEKEYCLOAKPASSWORD


