primehub:
  domain: primehub.10.88.88.88.xip.io:8080
jupyterhub:
  hub:
    db:
      type: sqlite-pvc
      pvc:
        storageClassName: local-path
  singleuser:
    storage:
      type: dynamic
      capacity: 10Gi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/app-root: http://primehub.10.88.88.88.xip.io:8080/hub
      nginx.ingress.kubernetes.io/use-port-in-redirects: true
    hosts:
    - primehub.10.88.88.88.xip.io
    path: /hub
keycloak:
  keycloak:
    persistence:
      dbPassword: CHANGEKEYCLOAKPASSWORD
      dbVendor: postgres
      deployPostgres: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - primehub.10.88.88.88.xip.io
      path: /auth
  persistence:
    deployPostgres: true
  postgresql:
    persistence:
      enabled: true
    postgresPassword: CHANGEKEYCLOAKPASSWORD
