jupyterhub:
  singleuser:
    profileList:
      - display_name: "Shared, CPU node"
        description: "cpu node"
        kubespawner_override:
          singleuser_image_spec: jupyter/minimal-notebook
      - display_name: "Data Science"
        description: "Data Science notebook from docker stacks"
        kubespawner_override:
          singleuser_image_spec: jupyter/datascience-notebook