---
# This values yaml is for ee installation
#
# Usage:
#   helm install primehub infuseai/primehub -f ee-values.yaml -f user-override.yaml

primehub:
  mode: ee

customImage:
  enabled: true

store:
  enabled: true
  #accessKey: "AKIAIOSFODNN7EXAMPLE"
  #secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  #bucket: "primehub"
  phfs:
    enabled: true
  logPersistence:
    enabled: false

jobSubmission:
  enabled: true
  artifact:
    enabled: true

usage:
  enabled: false

modelDeployment:
  enabled: true

adminNotebook:
  enabled: false
