apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "metacontroller.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "metacontroller.name" . }}
    helm.sh/chart: {{ include "metacontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "metacontroller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "metacontroller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ include "metacontroller.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/metacontroller"]
          args:
          - --logtostderr
          - -v=4
          - --discovery-interval=20s
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
