{{- if .Values.openshift.scc }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: primehub-openshift-ingress
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes", "routes/custom-host"]
  verbs:  ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: primehub-openshift-ingress-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: primehub-openshift-ingress
subjects:
- kind: ServiceAccount
  name: {{ include "primehub.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
{{- end }}
