{{- if .Values.openshift.scc }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: primehub-application
priority: 10
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- AUDIT_WRITE
- SYS_PTRACE
defaultAddCapabilities:
- AUDIT_WRITE
groups:
- system:authenticated
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
fsGroup:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:primehub-console
- system:serviceaccount:{{ .Release.Namespace }}:primehub-graphql
- system:serviceaccount:{{ .Release.Namespace }}:hub
- system:serviceaccount:{{ .Release.Namespace }}:primehub-admission
volumes:
- configMap
- secret
- persistentVolumeClaim
- downwardAPI
{{- end }}
