{{- if .Values.metacontroller.deploy }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metacontroller
  labels:
    app.kubernetes.io/name: metacontroller
spec:
  replicas: {{ .Values.metacontroller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: metacontroller
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metacontroller
    spec:
      serviceAccountName: metacontroller
      containers:
        - name: metacontroller
          image: "{{ .Values.metacontroller.image.repository }}:{{ .Values.metacontroller.image.tag }}"
          imagePullPolicy: {{ .Values.metacontroller.image.pullPolicy }}
          command: ["/usr/bin/metacontroller"]
          args:
          - --logtostderr
          - -v=4
          - --discovery-interval=20s
          resources:
{{ toYaml .Values.metacontroller.resources | indent 12 }}
    {{- with .Values.metacontroller.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.metacontroller.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.metacontroller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
