apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ include "primehub.name" . }}-fluentd
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        checksum/config-map: {{ include (print .Template.BasePath "/fluentd/configmap.yaml") . | sha256sum }}
        checksum/secret-map: {{ include (print .Template.BasePath "/fluentd/secret.yaml") . | sha256sum }}
    spec:
      serviceAccount: {{ include "primehub.name" . }}-fluentd
      serviceAccountName: {{ include "primehub.name" . }}-fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.11-debian-s3-1
        env:
        - name: FLUENT_UID
          value: "0"
        - name:  S3_BUCKET_NAME
          value: "primehub"
        - name:  S3_BUCKET_REGION
          value: "us-east-1"
        - name:  S3_ENDPOINT
          value: "http://minio.hub:9000/"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "primehub.name" . }}-fluentd
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "primehub.name" . }}-fluentd
              key: aws_secret_access_key
        resources: {}
        #  limits:
        #    memory: 200Mi
        #  requests:
        #    cpu: 100m
        #    memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-etc-volume
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-etc-volume
        configMap:
          name: {{ include "primehub.name" . }}-fluentd
