apiVersion: v1
kind: Secret
metadata:
  name: {{ include "primehub.name" . }}-fluentd
stringData:
  # This is temporary secret. Will use the same secret in primehub store.
  aws_access_key_id: 'AKIAIOSFODNN7EXAMPLE'
  aws_secret_access_key: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
