{{- if and .Values.keycloak.deploy .Values.keycloak.persistence.deployPostgres }}
{{- if (include "postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- if not .Values.keycloak.postgresql.postgresqlPassword }}
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
    {{- end }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "primehub.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }}
{{- end -}}
{{- end -}}
