{{ $RELEASE_NAME := (env "RELEASE_NAME" | default "primehub" ) }}
{{ $RELEASE_NAMESPACE := (env "RELEASE_NAMESPACE" | default "hub" ) }}
{{ $CHART_PATH := (env "CHART_PATH") }}
{{- if env "PRIMEHUB_AIRGAPPED" }}
{{ $CHART_PATH = "../charts/primehub" }}
{{- end }}
{{ $CHART_VERSION := (env "CHART_VERSION" | default "" ) }}

{{- if not $CHART_PATH }}
repositories:
  - name: infuseai
    url: https://charts.infuseai.io
{{- end }}

releases:
  - name: {{ $RELEASE_NAME }}
    namespace: {{ $RELEASE_NAMESPACE }}
    {{- if $CHART_PATH }}
    chart: {{ $CHART_PATH }}
    {{- else }}
    chart: infuseai/primehub
    version: {{ $CHART_VERSION }}
    {{- end }}
    values:
      - ../primehub/primehub.yaml.gotmpl
      - ../primehub/images.yaml.gotmpl
      {{- if (env "PRIMEHUB_VALUES_PATH") }}
      - {{ env "PRIMEHUB_VALUES_PATH" }}/primehub.yaml
      {{- end }}
