kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: primehub-bootstrap-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: primehub-bootstrap-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: primehub-bootstrap-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: primehub-bootstrap-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: primehub-bootstrap-secret-patch-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: primehub-bootstrap-secret-patch-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: primehub-bootstrap-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: primehub-bootstrap-secret-patch-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: primehub-bootstrap-sa
automountServiceAccountToken: true
