apiVersion: v1
kind: ConfigMap
metadata:
  name: primehub-bootstrap-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    app: primehub-bootstrap
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- tpl (.Files.Glob "scripts/*").AsConfig . | nindent 2 }}
