# The secret data will be populated by bootstrap job.
# Note that 'helm diff' will not show the data content,
# since they are considered local changes
apiVersion: v1
kind: Secret
metadata:
  name: primehub-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: primehub-bootstrap
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
