name: "Build PrimeHub Chart Release Tarball"
on:
  release:
    types:
      - created

jobs:
  build_release_tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{github.token}}
      - name: Build Release Tarball
        run: |
          ./ci/release.sh
      - name: Upload Release Tarball
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: primehub-${{ github.event.release.tag_name }}.tar.gz
          asset_name: primehub-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/tar+gzip
